[package]
name = "unid"
version ="0.1.6"
authors = [ "UNiD <>" ]
edition = "2018"
license-file = "LICENSE"
description = "Automate device security provisioning with edge intelligence."
homepage = "https://www.getunid.io"
documentation = "https://docs.getunid.io"
repository = "https://github.com/getunid/unid"
readme = "README.md"
keywords = [
  "iot",
  "embedded",
  "root-of-trust",
  "did",
]
categories = [
  "hardware-support",
  "external-ffi-bindings",
  "embedded",
  "cryptography",
  "no-std",
]
include = [
  "**/*.rs",
  "/bindings/**/*.c",
  "/bindings/**/*.h",
  "/bindings/**/*.json",
  "/Cargo.toml",
  "/Cargo.lock",
  "/CHANGELOG.md",
  "/LICENSE",
  "/README.md",
  "/SECURITY.md",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "unid"
crate-type = ["staticlib"]

[features]
default = ["std"]
std = []
alloc = []

[dependencies]
data-encoding = { version = "2.3.2" }
serde = { version = "1.0.131", features = ["derive"] }
serde_json = { version = "1.0.71" }

tokio = { version = "1", features = ["full"] }

# bip32 = { version = "0.4.0" }
digest = { version = "0.10.3" }
base64 = { version = "0.13.0" }
sha2 = { version = "0.10.2" }
k256 = { version = "0.10.4", features = ["ecdh", "ecdsa", "sha256", "keccak256", "serde"] }
hmac = { version = "0.12.1" }
scrypt = { version = "0.10.0", features = ["simple"] }
aes-gcm-siv = { git = "https://github.com/RustCrypto/AEADs.git", tag = "aes-gcm-siv-v0.11.0-pre" }

reqwest = { version = "0.11", features = ["blocking","json"] }
getrandom = { version = "0.2" }

colored = { version = "2" }

[dev-dependencies]
rstest = { version = "0.13.0" }

[profile.dev]
panic = "abort"
debug = true

[profile.test]
panic = "abort"
opt-level = 3
debug = true

[profile.release]
panic = "abort"
