[package]
name = "unid"
version ="0.1.6"
authors = [ "UNiD <>" ]
edition = "2018"
license-file = "LICENSE"
description = "Automate device security provisioning with edge intelligence."
homepage = "https://www.getunid.io"
documentation = "https://docs.getunid.io"
repository = "https://github.com/getunid/unid"
readme = "README.md"
keywords = [
  "iot",
  "embedded",
  "root-of-trust",
  "did",
]
categories = [
  "hardware-support",
  "external-ffi-bindings",
  "embedded",
  "cryptography",
  "no-std",
]
include = [
  "**/*.rs",
  "/bindings/**/*.c",
  "/bindings/**/*.h",
  "/bindings/**/*.json",
  "/Cargo.toml",
  "/Cargo.lock",
  "/CHANGELOG.md",
  "/LICENSE",
  "/README.md",
  "/SECURITY.md",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "unid"
crate-type = ["staticlib"]

[features]
default = ["std"]
std = []
alloc = []

[dependencies]
data-encoding = { version = "2.3.2", default-features = false, features = ["alloc"] }
base64 = { version = "0.13.0", default-features = false, features = ["alloc"] }
sha2 = { version = "0.9.8", default-features = false }
hmac = { version = "0.11.0", default-features = false }
cstr_core = "0.2.4"
libc = { version = "0.2.107", default-features = false }
serde = { version = "1.0.131", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0.71", default-features = false, features = ["alloc"] }
spin = { version = "0.9.2", default-features = false, features = ["mutex", "spin_mutex"] }
scrypt = { version = "0.8.0", default-features = false, features = ["simple"] }
subtle = { version = "2.4.1", default-features = false }
libsecp256k1-core = { version = "0.3.0", default-features = false }
crunchy = "0.2"
digest = "0.9"
hex = { version = "0.4.3", features = ["alloc"], default-features = false }

reqwest = { version = "0.11", features = ["blocking","json"] }
tokio = { version = "1", features = ["full"] }

getrandom = { version = "0.2" }
aes-gcm-siv = { version = "0.10.3" }
colored = { version = "2" }

k256 = { version = "0.10.0", default-features = false, features = ["ecdh", "ecdsa", "sha256", "keccak256", "serde"] }
hmac-drbg = { version = "0.3", default-features = false }
typenum = { version = "1.12", default-features = false }

arrayref = "0.3"




[dev-dependencies]
rstest = "0.12.0"

[profile.dev]
panic = "abort"
debug = true

[profile.test]
panic = "abort"
opt-level = 3
debug = true

[profile.release]
panic = "abort"
