name: docs
description: ""
inputs:
  github-token:
    required: true
    description: ""
  cargo-registry-token:
    required: true
    description: ""
runs:
  using: composite
  steps:
    - name: (checkout) source code
      uses: actions/checkout@v2

    - name: (setup) environment
      uses: ./.github/actions/shared

    - name: (docs) rustdoc
      shell: bash
      run: cargo doc

    - name: (docs) doxygen
      uses: mattnotmitt/doxygen-action@v1
