name: commit-analyzer
description: ""
inputs:
  github-token:
    required: true
    description: ""
outputs:
  version:
    description: ""
    value: ${{ steps.commit_analyzer.outputs.version }}
runs:
  using: composite
  steps:
    - name: (checkout) source code
      uses: actions/checkout@v2

    - name: (install) nodejs toolchain
      uses: actions/setup-node@v2

    - name: (run) commit-analyzer
      id: commit_analyzer
      shell: bash
      run: |
        yarn
        yarn semantic-release -b "${{ github.ref_name }}"

        [[ -f ".VERSION" ]] && {
          echo "version=$(cat .VERSION)" >> $GITHUB_OUTPUT
        } || {
          exit 1
        }