name: shared
description: ""
runs:
  using: composite
  steps:
    - name: (install) rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly

    - name: (install) nodejs toolchain
      uses: actions/setup-node@v2

    - name: (config) set nightly toolchain to default
      shell: bash
      run: rustup default nightly

    - name: (install) rust-src
      shell: bash
      run: rustup component add rust-src

    - name: (install) clippy
      shell: bash
      run: rustup component add clippy

    - name: (install) x86_64-unknown-linux-musl
      shell: bash
      run: rustup target add x86_64-unknown-linux-musl

    - name: (install) x86_64-pc-windows-msvc
      shell: bash
      run: rustup target add x86_64-pc-windows-msvc

    - name: (install) musl-tools
      shell: bash
      run: |
        apt-get update
        apt-get install -y musl-tools
